name: pomangam
description: 포만감 업주용 플러터 애플리케이션 (version_1.0)

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  provider: ^4.3.1

  dio: ^3.0.8

  shared_preferences: ^0.5.3+5

  injector: ^1.0.8

  modal_progress_hud: ^0.1.3

  json_annotation: ^3.0.1

  path: any

  time: ^1.2.0

  pull_to_refresh: ^1.6.2

  url_launcher: 5.1.2

  cached_network_image: ^2.0.0

  fluttertoast: ^7.1.1

  get: ^3.10.1

  firebase_messaging: 5.1.5

  firebase_core: ^0.4.0

  google_fonts: ^1.1.0

  auto_size_text: ^2.1.0

  shimmer: ^1.1.1

  persistent_bottom_nav_bar: ^2.0.5

  badges: ^1.1.3

  device_info: ^0.4.2+7

  firebase_crashlytics: ^0.1.4+1

  package_info: ^0.4.3

  flutter_staggered_animations: ^0.1.2

  flutter_animation_set: ^0.0.4

  circular_countdown_timer: ^0.0.7

  flutter_slidable: ^0.5.7

  flutter_calendar_carousel: ^1.4.11

  neat_periodic_task: ^1.0.1

  wakelock: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0

  json_serializable: ^3.3.0

  flutter_launcher_icons: ^0.7.3

flutter_icons:
  android: "launcher_icon"

  ios: true

  image_path: "assets/logo3.png"

flutter:
  uses-material-design: true

  assets:
    - assets/